global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "users"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [
        "users:8080"
      ]
  - job_name: "main"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [
        "main:8081"
      ]
  - job_name: "otc"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [
        "otc:8082"
      ]
  - job_name: "client"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [
        "client:8083"
      ]